#[derive(Deserialize)]
pub struct UpdatedEventForm {
    pub name: String,
    pub type: EventType,
    pub semester: String,
    pub call_time: String,
    pub call_date: String,
    pub release_time: String,
    pub release_date: String,
    pub performance_time: Option<String>,
    pub points: i32,
    pub comments: String,
    pub location: String,
    pub gig_count: Option<String>,
    pub section: Option<String>,
    pub default_attend: Option<String>,
    pub is_private: Option<String>,
    pub uniform: String,
    pub contact_name: String,
    pub contact_email: String,
    pub contact_phone: String,
    pub price: Option<i32>,
    pub public: Option<String>,
    pub summary: String,
    pub description: String,
}
