[package]
name = "mysql_dump"
version = "0.1.0"
authors = ["Sam Mohr <sam.mohr@protonmail.com>"]
edition = "2018"

[dependencies]
http = "*"
cgi = "*"
mysql = "16"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
url = "*"
chrono = { version = "*", features = ["serde"] }
