[package]
name = "grease"
version = "0.1.0"
authors = ["Sam Mohr <sam@mohr.codes>"]
edition = "2018"

[dependencies]
async-graphql = { version = "2.8.3", features = ["chrono", "dataloader"] }
async-trait = "0.1"
backtrace = "0.3"
base64 = "0.10"
bcrypt = "0.4"
cgi = "0.2"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.14.1"
glob = "0.3"
itertools = "0.8.2"
icalendar = "0.8"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sqlx = { version = "0.4.1", features = ["runtime-tokio-rustls", "mysql", "offline"] }
tokio = { version = "1.5.0", features = ["full"] }
url = "1.7.2"
uuid = { version = "0.7", features = ["v4"] }
zip = "0.5"
