[package]
name = "migration_script"
version = "0.1.0"
authors = ["Sam Mohr <sam.mohr@protonmail.com>"]
edition = "2021"

[dependencies]
bcrypt = "0.4"
chrono = { version = "0.4", features = ["serde"] }
mysql = "16.0"
structopt = "0.2"
url = "1.7.2"
