[package]
name = "extract_derive"
version = "0.1.0"
authors = ["Sam Mohr <sammohr97@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.13.1"
quote = "0.5.1"
serde = { version = "*", features = ["derive"] }
